export const steps = [
  {
    stepIndex: 0,
    title: "Odaberite Proizvođača vašeg vozila",
    text: "",
    options: [
      "Peugeot",
      "Volkswagen",
      "Citroen",
      "Audi",
      "Bmw",
      "Seat",
      "Alfa Romeo",
      "Kia",
      "Hyundai",
      "Honda",
      "Toyota",
    ],
    type: "radio-button",
  },
  {
    stepIndex: 1,
    title: "Odaberite jednu ili više usluga za koju ste",
    text: "",
    options: [
      { service: "Zamjena ulja i filtera", price: 500 },
      { service: "Promjena pakni", price: 450 },
      { service: "Promjena guma", price: 100 },
      { service: "Servis klima uređaja ", price: 299 },
      { service: "Balansiranje guma", price: 50 },
      { service: "Zamjena guma u kočnicama", price: 229 },
    ],
    type: "checkbox",
  },
  {
    stepIndex: 2,
    title: "Vaši kontakt podaci",
    text: "",
    options: [
      { title: "Ime i prezime", code: "name" },
      { title: "Email adresa", code: "email" },
      { title: "Broj telefona", code: "phoneNumber" },
      { title: "Napomena (opcionalno)", code: "note" },
    ],
    type: "text-input",
  },
  {
    stepIndex: 3,
    title: "Pregled i potvrda vašeg odabira",
    text: "Molimo vas da još jednom pregledate i potvrdite unesene podatke. Ukoliko želite promijeniti neki od podataka, možete pritisnuti gumb za uređivanje pored svake od kategorija. Kada ste provjerili i potvrdili ispravnost svojih podataka, pritisnite gumb pošalji na dnu, za slanje upita na servis.",
    options: ["MODEL VOZILA", "ODABRANE USLUGE", "KONTAKT PODACI"],
    type: "summary",
  },
  {
    stepIndex: 4,
    title: "Vaša prijava je uspješno poslana",
    text: "Vaša prijava je uspješno poslana i zaprimljena. Kontaktirat ćemo vas u najkraćem mogućem roku. Hvala vam.",
    options: [],
    type: "finish",
  },
];
